apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taxi-stage
spec:
  project: default
  destination:
    namespace: stage-environment
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/bigkevmcd/taxi-stage-config.git
    path: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
