apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taxi-stage
spec:
  project: default
  destination:
    namespace: stage-environment
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GITHUB_STAGE_REPO.git
    path: deploy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
