apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taxi-demo
spec:
  project: default
  destination:
    namespace: taxi
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GITHUB_REPO.git
    path: deploy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
